project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  favicon: "images/favicon.png"
  search:
    location: navbar
    type: overlay
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Blog
        href: blog.qmd
      - text: Resume
        href: resume.qmd
    right:
      - icon: github
        href: https://github.com/sirplantman
      - icon: linkedin
        href: https://www.linkedin.com/in/gabeguzman/
      - icon: clipboard2-data-fill # Kaggle icon does not exist in Bootstrap. Find alternative
        href: https://www.kaggle.com/sirplantman
      - icon: envelope-fill
        # href: (mailto:gabeguzman08@gmail.com){target="_blank"}
format:
  html:
    page-layout: full
    theme: darkly
    css: styles.css
    fontsize: 0.85em
    highlight-style: printing
    code-block-bg: "#E5E4E2"
    code-overflow: wrap
execute:
  echo: true
