project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  favicon: "images/favicon.png"
  page-footer:
    center: |
      <span class="container"><strong>[Contact: Gabriel Guzman](mailto:gabeguzman08@gmail.com){target="_blank"}</strong></span>
    left: |
      <span class="container"><strong>Made with [Posit Quarto](https://quarto.org/){target="_blank"}</strong></span>
    right: |
      <span class="container"><strong>[Github Repo](https://github.com/sirplantman){target="_blank"}</strong></span>
    background: "#1c1c1e"
  search:
    location: navbar
    type: overlay
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Blog
        href: blog.qmd
      - text: Resume
        href: resume.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/sirplantman
      - icon: linkedin
        href: https://www.linkedin.com/in/gabeguzman/
format:
  html:
    theme: lux
    css: styles.css
    code-fold: show
    code-link: true
    highlight-style: github
    code-block-border-left: "#ceccca"
    code-block-bg: true
